AWSTemplateFormatVersion: "2010-09-09"
Description: >
    Template para criar a role administrativa
    que tem controle total sobre os dois buckets.
Parameters:
    AuditAdminRoleName:
       Type: string
       Default: AuditAdminRole
       Description: Nome da role.
    LoggingBucketArn:
       Type: string
       Description: arn do bucket principal.
    LoggingBucketSrtArn:
       Type: string
       Description: arn do bucket-srt.
    TrustedIdentityArn:
       Type: string
       Description: arn da identidade confiável.
    ManagedPolicyName:
       Type: string
       Description: nome da politica anexada a role.
Resources:
    AuditAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AuditAdminRoleName
      ManagedPolicyArns:
        - !Ref AuditAdminRolePolicy
      AssumeRolePolicyDocument:
        Version: "2010-10-09"
        Statement:
          - Sid: AuditAdminRoleTrust
            Effect: Allow
            Principal: !Ref TrustedIdentityArn
            Actions:
            - sts:AssumeRole
    AuditRoleManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
       ManagedPolicyName: !Ref ManagedPolicyName
       ManagedPolicyDocument:
          Version: "2010-10-07"
          Statement:
          - Sid: AuditRoleManagedPolicy
            Effect: Allow
            Actions:
            - s3:*
            Resources:
            - !Ref LoggingBucketArn
            - !Ref LoggingBucketSrtArn

Outputs:
  AuditRoleArn:
    Description:
    Value: !Ref AuditAdminRole
       
                
            
      
