AWSTemplateFormatVersion: "2010-09-09"
Description: Cria uma IAM Role de auditoria.

Parameters:
  AuditRole:
    Type: String
    Description: Nome da role de auditoria.

  AuditRolePolicy:
    Type: String
    Description: Nome da managed policy.

  TrustedPrincipalArn:
    Type: String
    Description: ARN do principal que pode assumir a role.

  LoggingBucket:
    Type: String
    Description: Nome do bucket de logs.

  LoggingBucketSrt:
    Type: String
    Description: Nome do bucket SRT.

Resources:
  AuditRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref AuditRolePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AuditRolePolicyAllow
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              - !Sub "arn:aws:s3:::${LoggingBucket}/*"
              - !Sub "arn:aws:s3:::${LoggingBucketSrt}/*"

          - Sid: AuditRolePolicyAllowBkt
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
            Resource:
              - !Sub "arn:aws:s3:::${LoggingBucket}"
              - !Sub "arn:aws:s3:::${LoggingBucketSrt}"

          - Sid: AuditRolePolicyDeny
            Effect: Deny
            Action:
              - s3:PutObject
              - s3:DeleteObject
              - s3:DeleteObjectVersion
              - s3:PutObjectRetention
              - s3:BypassGovernanceRetention
              - s3:PutObjectLegalHold
            Resource:
              - !Sub "arn:aws:s3:::${LoggingBucket}/*"
              - !Sub "arn:aws:s3:::${LoggingBucketSrt}/*"

  AuditRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref AuditRole
      ManagedPolicyArns:
        - !Ref AuditRolePolicy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AuditRoleAccess
            Effect: Allow
            Principal:
              AWS: !Ref TrustedPrincipalArn
            Action: sts:AssumeRole

Outputs:
  AuditRoleArn:
    Description: ARN da AuditRole
    Value: !GetAtt AuditRole.Arn

  AuditRolePolicyArn:
    Description: ARN da Managed Policy anexada
    Value: !Ref AuditRolePolicy
