AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Dois buckets S3 de acordo com o que foi especificado no projeto.

Parameters:

  LoggingBucket:
    Type: String
    Description: Nome do bucket 1

  LoggingBucketSrt:
    Type: String
    Description: Nome do bucket 2

  RetentionDays:
    Type: Number
    Default: 90
    MinValue: 1
    MaxValue: 166
    ConstraintDescription: >
      RetentionDays não pode ser maior que 166 dias,
      pois o BucketTwo expira objetos nesse prazo.
    Description: Retenção padrão do Object Lock em modo GOVERNANCE

Resources:

  BucketOne:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LoggingBucket

      ObjectLockEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Mode: GOVERNANCE
            Days: !Ref RetentionDays

      VersioningConfiguration:
        Status: Enabled

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      LifecycleConfiguration:
        Rules:
          - Id: CurrentVersion-IA45-DeepArchive165-Expire731
            Status: Enabled
            Prefix: ""
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 45
              - StorageClass: DEEP_ARCHIVE
                TransitionInDays: 165
            ExpirationInDays: 731

  BucketTwo:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LoggingBucketSrt

      ObjectLockEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Mode: GOVERNANCE
            Days: !Ref RetentionDays

      VersioningConfiguration:
        Status: Enabled

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      LifecycleConfiguration:
        Rules:
          - Id: CurrentVersion-IA45-Expire166
            Status: Enabled
            Prefix: ""
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 45
            ExpirationInDays: 166

Outputs:
  BucketOneOut:
    Value: !Ref BucketOne
    Description: Bucket 1

  BucketTwoOut:
    Value: !Ref BucketTwo
    Description: Bucket 2
