AWSTemplateFormatVersion: "2010-09-09"

Description: Template para criar as duas bucket policies.

Parameters:

  LoggingBucket:
    Type: String
    Description: Nome do primeiro bucket.
    
  LoggingBucketSrt:
    Type: String
    Description: Nome do segundo bucket.
    
  AuditAdminArn:
    Type: String
    Description: ARN da role administrativa.
    
  RsyslogRoleArn:
    Type: String
    Description: ARN da role do Rsyslog.
    
  AuditRoleArn:
    Type: String
    Description: ARN da role de auditoria.
    
Resources:

  BucketPolicyOne:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref LoggingBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: DenyBucketAccess
              Effect: Deny
              NotPrincipal:
                AWS:
                  - !Ref AuditAdminArn
                  - !Ref RsyslogRoleArn
                  - !Ref AuditRoleArn
              Action: "s3:*"
              Resource:
                - !Sub "arn:aws:s3:::${LoggingBucket}"
                - !Sub "arn:aws:s3:::${LoggingBucket}/*"
  
            - Sid: DenyInsecureTransport
              Effect: Deny
              Principal: "*"
              Action: "s3:*"
              Resource:
                - !Sub "arn:aws:s3:::${LoggingBucket}"
                - !Sub "arn:aws:s3:::${LoggingBucket}/*"
              Condition:
                Bool:
                  aws:SecureTransport: false
  
            - Sid: AllowRsyslogAccess
              Effect: Allow
              Principal:
                AWS: !Ref RsyslogRoleArn
              Action:
                - s3:PutObject
                - s3:AbortMultipartUpload
              Resource: !Sub "arn:aws:s3:::${LoggingBucket}/*"
  
            - Sid: AllowRsyslogAccessBkt
              Effect: Allow
              Principal:
                AWS: !Ref RsyslogRoleArn
              Action: s3:ListBucket
              Resource: !Sub "arn:aws:s3:::${LoggingBucket}"
  
            - Sid: AllowAuditAccessBkt
              Effect: Allow
              Principal:
                AWS: !Ref AuditRoleArn
              Action:
                - s3:ListBucket
                - s3:GetBucketLocation
              Resource: !Sub "arn:aws:s3:::${LoggingBucket}"
  
            - Sid: AllowAuditAccess
              Effect: Allow
              Principal:
                AWS: !Ref AuditRoleArn
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
              Resource: !Sub "arn:aws:s3:::${LoggingBucket}/*"
              
  BucketPolicyTwo:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref LoggingBucketSrt
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: DenyBucketAccess
              Effect: Deny
              NotPrincipal:
                AWS:
                  - !Ref AuditAdminRole
                  - !Ref RsyslogRoleArn
                  - !Ref AuditRoleArn
              Action: "s3:*"
              Resource:
                - !Sub "arn:aws:s3:::${LoggingBucketSrt}"
                - !Sub "arn:aws:s3:::${LoggingBucketSrt}/*"
  
            - Sid: DenyInsecureTransport
              Effect: Deny
              Principal: "*"
              Action: "s3:*"
              Resource:
                - !Sub "arn:aws:s3:::${LoggingBucketSrt}"
                - !Sub "arn:aws:s3:::${LoggingBucketSrt}/*"
              Condition:
                Bool:
                  aws:SecureTransport: false
  
            - Sid: AllowRsyslogAccess
              Effect: Allow
              Principal:
                AWS: !Ref RsyslogRoleArn
              Action:
                - s3:PutObject
                - s3:AbortMultipartUpload
              Resource: !Sub "arn:aws:s3:::${LoggingBucketSrt}/*"
  
            - Sid: AllowRsyslogAccessBkt
              Effect: Allow
              Principal:
                AWS: !Ref RsyslogRoleArn
              Action: s3:ListBucket
              Resource: !Sub "arn:aws:s3:::${LoggingBucketSrt}"
  
            - Sid: AllowAuditAccessBkt
              Effect: Allow
              Principal:
                AWS: !Ref AuditRoleArn
              Action:
                - s3:ListBucket
                - s3:GetBucketLocation
              Resource: !Sub "arn:aws:s3:::${LoggingBucketSrt}"
  
            - Sid: AllowAuditAccess
              Effect: Allow
              Principal:
                AWS: !Ref AuditRoleArn
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
              Resource: !Sub "arn:aws:s3:::${LoggingBucketSrt}/*"
              
Outputs:
  BucketPolicy01:
    Value: !Ref BucketPolicyOne
    Description: Identificador da politica.
  BucketPolicy02:
    Value: !Ref BucketPolicyTwo
    Description: Identificador da politica.
