AWSTemplateFormatVersion: "2010-09-09"
Description: >
  IAM Roles Anywhere: cria Trust Anchor, Profile,
  IAM Role com trust policy baseada em principal tags x509 e SourceArn do TrustAnchor,
  e uma IAM Managed Policy para acesso a dois buckets S3.

Parameters:
  TrustAnchorName:
    Type: String
    Description: Nome do Trust Anchor.

  ProfileName:
    Type: String
    Description: Nome do Profile.

  X509SanUri:
    Type: String
    Description: Valor esperado para aws:PrincipalTag/x509SAN/URI

  X509SubjectCN:
    Type: String
    Description: Valor esperado para aws:PrincipalTag/x509Subject/CN

  X509IssuerCN:
    Type: String
    Description: Valor esperado para aws:PrincipalTag/x509Issuer/CN

  RsyslogRoleName:
    Type: String
    Default: RsyslogRolesAnywhereAccess
    Description: Nome da IAM Role

  RsyslogRolePolicyName:
    Type: String
    Default: RsyslogS3WritePolicy
    Description: Nome da IAM Managed Policy

  LoggingBucket:
    Type: String
    Description: Nome do bucket 1

  LoggingBucketSrt:
    Type: String
    Description: Nome do bucket 2

Resources:
  TrustAnchor:
    Type: AWS::RolesAnywhere::TrustAnchor
    Properties:
      Name: !Ref TrustAnchorName
      Enabled: true
      Source:
        SourceData:
          X509CertificateData: |
            -----BEGIN CERTIFICATE-----
            MIIFjjCCA3agAwIBAgIUDTiUeuq7EvG+50Z2OUfVVYrRtygwDQYJKoZIhvcNAQEL
            BQAwUDELMAkGA1UEBhMCQlIxCzAJBgNVBAgMAlNQMQwwCgYDVQQHDANTQk8xDjAM
            BgNVBAoMBWNhbXB5MRYwFAYDVQQDDA1jYW1weSByb290IENBMB4XDTI2MDIwMTE3
            NDAzOFoXDTM2MDEzMDE3NDAzOFowUDELMAkGA1UEBhMCQlIxCzAJBgNVBAgMAlNQ
            MQwwCgYDVQQHDANTQk8xDjAMBgNVBAoMBWNhbXB5MRYwFAYDVQQDDA1jYW1weSBy
            b290IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAnsSZjwQqfu+y
            HgnM+f6SRMTKhqtwsc/Ulc1WMIsAFqu95w+tJln9n9OZvssxGQm6DfAvCbfgZqu/
            UF/jfyM8LpwDT2o+zXf/BUOtPZ59rJuiYb+6i87ndxM4lYBcV5ZOe9/dy4Xs4zlE
            Zlulv0OdkBYHycjTGImWynMzCAd6B29gUOvWWTFFr7NXAvoMNkalPtqQPNZXhCSi
            7LYkx6ylsUX42EIKnm7VPupt8N6D2deR1+XvWaplaeDVoZMJwddw1Mo1c2dvaFfN
            xU0LzBrjrYjzfsI/vJtMJwyx8od8g+o/lyKHbYO6/nQUXgAtNQe6JgSq2mlU0eQV
            fUENI4BWYN+NxhymtrR8SvL1m2gLy6D4Dourkene0d36kuTb+Ia/T79IGM9A0pNL
            N2irGwv77A9iLYxyOG/hErZ4n5JzcHWdJIqv1vLnslML5KNS5+Vtl9yebfC4tU42
            zxYfjBBUSeNlJjXeGvMzJCXMmJpJgCN6yU8zIMfpOvhtweT5kSR7CHzjb2RyDR9E
            8XEK9YHzFhA1A91QlTP05esuKzEwExSEBpUfFcfadzYCM5ucSv7DGxC8dWy31+wK
            wILWxDonHIEp49ELM1ZYcOX+GWRB5ylA1d5NK9MsEU/KPdvKgZWQxaflVtRuAoqr
            +WCDY8kGb18UsLvU3mh0NjxGoREbes8CAwEAAaNgMF4wDwYDVR0TAQH/BAUwAwEB
            /zALBgNVHQ8EBAMCAQYwHQYDVR0OBBYEFEuSuLBWV8DzILCYNIuIA86pyPewMB8G
            A1UdIwQYMBaAFEuSuLBWV8DzILCYNIuIA86pyPewMA0GCSqGSIb3DQEBCwUAA4IC
            AQCXnhfISxZ+B5JJrk5czBzqXV9Sdk39n2mnmKKbPyle+8UP2wp1v7p60Qwc6UwV
            bvmWSQukRpF1eEJBKSzd1tYQth1ZDwN3bdGTtPK14oWHSxXGEG7g5euZyD4l9rjX
            71LRVo3eO5V2tR5ORD6HIxFX3pQ+IZF8lEcb6d+kXL82/+wmQTaBUeetcTgBXK/V
            rrbq8koGTTUc3D1auwSvWrgmg9YVTykyvfaSqFg1QpfgDVZQ4vox6rormHOyHM+q
            rnNiIq8lp4SAiClBB0n6CedgxzBVxhkWT8JC0hO9vIAVsXo5OOFPY47EzUs6yMhh
            dSnd6r9PFo9tMxR76/+EMXGBeA6iqwcuSUxNHNa66XRYjDP6ApTEVoVB8dS7IO4T
            XpONmGceGk65h8vxyJcb5RlHMjCmEBhgWaQ5cxPzOso/tLw+NY8VIz2mpaTPQ0Gu
            xoICsPRiFOQs2EQqDB4Oy1ku1iDgO1iad7ti8XXsSASDMDE82JYZGz/N3r1wb8PY
            LGqplE/pRoBp0a/iK13+lY6eVg0G8y09bKTC4jojoNxQ8xZ6ibYUHrmEoZkAma/H
            Ip+PYGGK0FDxc3FMJ/ewNmf4MH98lckYV4Vu48Ykhor3c3BCAnkcTWrJYLMdmVIj
            Hr0hOzUnuUu3ucrm2dXSa+WX2fzMuN7QIMaEuKOuywQvoA==
            -----END CERTIFICATE-----
        SourceType: CERTIFICATE_BUNDLE

  RsyslogS3Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref RsyslogRolePolicyName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: RsyslogAccess
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:AbortMultipartUpload
            Resource:
              - !Sub "arn:aws:s3:::${LoggingBucket}/*"
              - !Sub "arn:aws:s3:::${LoggingBucketSrt}/*"

          - Sid: RsyslogAccessBkt
            Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${LoggingBucket}"
              - !Sub "arn:aws:s3:::${LoggingBucketSrt}"

  RsyslogRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RsyslogRoleName
      ManagedPolicyArns:
        - !Ref RsyslogS3Policy
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: RsyslogLoggingBucketAccess
            Effect: Allow
            Principal:
              Service: rolesanywhere.amazonaws.com
            Action:
              - sts:AssumeRole
              - sts:SetSourceIdentity
              - sts:TagSession
            Condition:
              StringEquals:
                aws:PrincipalTag/x509SAN/URI: !Ref X509SanUri
                aws:PrincipalTag/x509Subject/CN: !Ref X509SubjectCN
                aws:PrincipalTag/x509Issuer/CN: !Ref X509IssuerCN
              ArnEquals:
                aws:SourceArn: !GetAtt TrustAnchor.TrustAnchorArn

  Profile:
    Type: AWS::RolesAnywhere::Profile
    Properties:
      Name: !Ref ProfileName
      Enabled: true
      RoleArns:
        - !GetAtt RsyslogRole.Arn
      DurationSeconds: 3600
      AttributeMappings:
        - CertificateField: x509SAN
          MappingRules:
            - Specifier: URI
        - CertificateField: x509Subject
          MappingRules:
            - Specifier: CN
        - CertificateField: x509Issuer
          MappingRules:
            - Specifier: CN

Outputs:
  TrustAnchorArn:
    Description: ARN do Trust Anchor
    Value: !GetAtt TrustAnchor.TrustAnchorArn

  ProfileArn:
    Description: ARN do Profile
    Value: !GetAtt Profile.ProfileArn

  RoleArn:
    Description: ARN da Role
    Value: !GetAtt RsyslogRole.Arn

  ManagedPolicyArn:
    Description: ARN da Managed Policy
    Value: !Ref RsyslogS3Policy
